wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710872801.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      4: 3.12.2
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
